version: '3.8'

services:
  expo:
    build: .
    ports:
      - "19000:19000" # Expo's main port
      - "19001:19001" # Expo's tunnel port
      - "19002:19002" # Expo's debugger port
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
